name: Simple Jira Update

on:
  push:
    branches: [ main ]

jobs:
  jira-update:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Jira
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Find Jira issue in commit
        id: find
        uses: atlassian/gajira-find-issue-key@v3
        with:
          string: ${{ github.event.head_commit.message }}
          
      - name: Echo found issue
        run: echo "Found issue ${{ steps.find.outputs.issue }}"
        
      - name: Update Jira (if issue found)
        if: steps.find.outputs.issue != ''
        uses: atlassian/gajira-comment@v3
        with:
          issue: ${{ steps.find.outputs.issue }}
          comment: "🚀 Deployed to production from commit ${{ github.sha }} by ${{ github.actor }}"
